# buildspec.yml
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
      python: 3.9
    commands:
      - npm install aws-cdk -g
      - python -m venv .venv
      - source .venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - cdk deploy
